version: '3'

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    command: /venv/bin/python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./back:/code
      - ./back/static:/static
      - ./back/media:/media
  nuxt:
    build:
      context: ./front
    restart: always
    volumes:
      - ./logs:/src/root/.npm/_logs
    ports:
      - "3000:3000"
    command:
      "npm run start"
